# Generated by Django 3.0 on 2020-10-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('1', 'Very Important'), ('2', 'Important'), ('3', 'Okay')], max_length=2)),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
