# Generated by Django 3.1.2 on 2020-12-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0005_auto_20201203_1000'),
        ('phaseone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageForm',
        ),
    ]
