# Generated by Django 3.1.2 on 2020-12-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phaseone', '0002_delete_messageform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForm',
            fields=[
                ('priority', models.CharField(choices=[('1', 'Very Important'), ('2', 'Important'), ('3', 'Okay')], max_length=2)),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
