# Generated by Django 3.1.2 on 2020-12-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phaseone', '0003_messageform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageform',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
